version: '2'
services:

  postgres:
    image: postgres:11-alpine
    container_name: "postgres-database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  my-quarkus-app:
    container_name: quarkus-app
    image: quarkus-sample-jvm:latest
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      MY_NAME: "Evyatar"
    depends_on:
      - postgres