version: "3.7"
services:
  estoque.api:
    container_name: estoque2
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"