version: '2'
services:

  postgres:
    image: postgres:11-alpine
    container_name: "postgres-database"
    ports:
      - "5432:5432"
    networks:
      - myytnetwork
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  frontend:
    container_name: frontend
    image: estoque
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - myytnetwork
    depends_on:
      - postgres

  my-quarkus-app:
    container_name: quarkus-app
    image: api-quarkus-estoque9:latest
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - myytnetwork
    depends_on:
      - postgres
      - frontend

networks:
  myytnetwork:
    driver: bridge